=== TMassoC/lenguajedemarcas/pruebas/pruebas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="salud">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="servicios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fisioterapia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="precio_sesion"
                                                        type="xs:string" />
                                                    <xs:element name="bono5" type="xs:string" />
                                                    <xs:element name="bono10" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="dias">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hora" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="reserva" type="xs:string" />
                                        <xs:element name="empleados">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="empleado"
                                                        maxOccurs="unbounded" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="podologia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="precio_sesion"
                                                        type="xs:string" />
                                                    <xs:element name="bono5" type="xs:string" />
                                                    <xs:element name="bono10" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="dias">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hora" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="reserva" type="xs:string" />
                                        <xs:element name="empleados">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="empleado" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="psicologia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="precio_sesion"
                                                        type="xs:string" />
                                                    <xs:element name="bono5" type="xs:string" />
                                                    <xs:element name="bono10" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="dias">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hora" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="reserva" type="xs:string" />
                                        <xs:element name="empleados">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="empleado" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="yoga">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="precio_mes" type="xs:string" />
                                        <xs:element name="plazas" type="xs:string" />
                                        <xs:element name="dias">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hora" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="empleados">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="empleado"
                                                        maxOccurs="unbounded" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pilates">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="plazas" type="xs:string" />
                                        <xs:element name="dias">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hora" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="empleado" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="meditacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="plazas" type="xs:string" />
                                        <xs:element name="dias">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hora" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="empleados">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="empleado"
                                                        maxOccurs="unbounded" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TMassoC/lenguajedemarcas/examen/pruebas.xml
<?xml version="1.0" encoding="UTF-8"?>
<salud xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="pruebas.xsd">
    <servicios>
        <!--FISIOTERAPIA-->
        <fisioterapia> 
            <precio>
                <precio_sesion>35€/h</precio_sesion>
                <bono5>160€</bono5>
                <bono10>300€</bono10>
            </precio>
            <dias>
                <dia>lunes</dia>
                <dia>martes</dia>
                <dia>miercoles</dia>
                <dia>jueves</dia>
                <dia>viernes</dia>
            </dias>
            <horas>
                <hora>9:00 - 13:00 </hora>
                <hora>15:00 - 19: 00 </hora>
            </horas>
            <reserva>previa</reserva>
            <empleados>
                <empleado>Chus</empleado>
                <empleado>Marga</empleado>
                <empleado>Silvia</empleado>
            </empleados>
        </fisioterapia>
        <!--PODOLOGIA-->
        <podologia>
            <precio>
                <precio_sesion>25€/h</precio_sesion>
                <bono5>100€</bono5>
                <bono10>190€</bono10>
            </precio>
            <dias>
                <dia>lunes</dia>
                <dia>martes</dia>
                <dia>miercoles</dia>
                <dia>jueves</dia>
                <dia>viernes</dia>
            </dias>
            <horas>
                <hora>9:00 - 13:00 </hora>
                <hora>15:00 - 19: 00 </hora>
            </horas>
            <reserva>previa</reserva>
            <empleados>
                <empleado>Joana</empleado>
            </empleados>
        </podologia>
        <!--PSICOLOGIA-->
        <psicologia>
            <precio>
                <precio_sesion>50€/h</precio_sesion>
                <bono5>220€</bono5>
                <bono10>400€</bono10>
            </precio>
            <dias>
                <dia>lunes</dia>
                <dia>martes</dia>
                <dia>miercoles</dia>
                <dia>jueves</dia>
                <dia>viernes</dia>
            </dias>
            <horas>
                <hora>9:00 - 13:00 </hora>
                <hora>15:00 - 19: 00 </hora>
            </horas>
            <reserva>previa</reserva>
            <empleados>
              <empleado>Aina</empleado>  
            </empleados>        
        </psicologia>
        <!--YOGA-->
        <yoga>
            <precio_mes>25€/mes</precio_mes>
            <plazas>20 personas</plazas>
            <dias>
                <dia>lunes</dia>
                <dia>miercoles</dia>
                <dia>viernes</dia>
            </dias>
            <horas>
                <hora>11:00 - 12:30</hora>
                <hora>17:00 - 18:30</hora>
            </horas>
            <empleados>
                <empleado>Biel</empleado>
                <empleado>Alex</empleado>
            </empleados>
        </yoga>
        <!--PILATES-->
        <pilates>
            <precio>30€/mes</precio>
            <plazas>25 personas</plazas>
            <dias>
                <dia>martes</dia>
                <dia>jueves</dia>
                <dia>viernes</dia>
            </dias>
            <horas>
                <hora>10:00 - 11:30</hora>
                <hora>16:00 - 17:30</hora>
            </horas>
            <empleado>Tolo</empleado>
        </pilates>
        <!--MEDITACION-->
        <meditacion>
            <precio>35€/mes</precio>
            <plazas>10 personas</plazas>
            <dias>
                <dia>lunes</dia>
                <dia>martes</dia>
                <dia>miercoles</dia>
                <dia>jueves</dia>
                <dia>viernes</dia>
            </dias>
            <horas>
                <hora>10:00 - 11:00</hora>
                <hora>19:00 - 20:00</hora>
            </horas>
            <empleados>
                <empleado>Biel</empleado>
                <empleado>Alex</empleado>
            </empleados>
        </meditacion>
    </servicios>
</salud>
